// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6afaaWol2FgFjFxjuCMdmqRfA-OItnew',
    appId: '1:59821550598:web:1546c810312e868e1aa787',
    messagingSenderId: '59821550598',
    projectId: 'ambulance-3e451',
    authDomain: 'ambulance-3e451.firebaseapp.com',
    storageBucket: 'ambulance-3e451.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDknAWwdVsqmOcknGcNxxo_QhMuxCTUdn8',
    appId: '1:59821550598:android:83163a6feee87eab1aa787',
    messagingSenderId: '59821550598',
    projectId: 'ambulance-3e451',
    storageBucket: 'ambulance-3e451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8fYJSSVGKpc-Ks7SpbueRvigQandktp8',
    appId: '1:59821550598:ios:dff56b86e75c67a81aa787',
    messagingSenderId: '59821550598',
    projectId: 'ambulance-3e451',
    storageBucket: 'ambulance-3e451.appspot.com',
    iosClientId: '59821550598-n0i5uvt3deqs3oo1497u0atqavb5s79t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambulanceAlertApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8fYJSSVGKpc-Ks7SpbueRvigQandktp8',
    appId: '1:59821550598:ios:dff56b86e75c67a81aa787',
    messagingSenderId: '59821550598',
    projectId: 'ambulance-3e451',
    storageBucket: 'ambulance-3e451.appspot.com',
    iosClientId: '59821550598-n0i5uvt3deqs3oo1497u0atqavb5s79t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ambulanceAlertApp',
  );
}
